FROM ubuntu:12.04.5

# Because there is no package cache in the image, you need to run:
RUN apt-get update

# Install nodejs
RUN apt-get install curl -y
RUN apt-get install python-software-properties -y
#RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
#RUN apt-get update
#RUN apt-get install -y nodejs

# Use NVM to manage node
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
nvm install 4
nvm install 5
nvm install 6
nvm install 7
nvm install 8

# Install smartwrap
RUN apt-get install git -y
RUN git clone --branch 2.x https://www.github.com/tecfu/smartwrap

# Install grunt
RUN npm install grunt-cli -g

WORKDIR /smartwrap

# Manual Phantomjs install
RUN apt-get install wget -y
RUN apt-get install bzip2 -y
RUN apt-get install libfontconfig1 -y
RUN cd /usr/local/share/
RUN wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.6-linux-x86_64.tar.bz2
RUN ls
RUN tar xjf phantomjs-1.9.6-linux-x86_64.tar.bz2
RUN rm -f phantomjs-1.9.6-linux-x86_64.tar.bz2
RUN ln -s phantomjs-1.9.6-linux-x86_64 phantomjs
RUN ln -s /usr/local/share/phantomjs/bin/phantomjs /usr/bin/phantomjs

#RUN npm uninstall -D grunt-mocha
#RUN npm i grunt-mocha@0.4.13 
RUN npm install 

# Run unit tests
RUN node -v
RUN cat package.json

# Run unit tests
nvm use 4
RUN grunt t

nvm use 5
RUN grunt t

nvm use 6
RUN grunt t

nvm use 7
RUN grunt t

nvm use 8
RUN grunt t
